# Generated by Django 3.0.8 on 2020-08-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200816_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='site_image',
            field=models.ImageField(default='default.jpg', upload_to='profilepics'),
        ),
    ]
